config = {
    achievements: true,
    allowEdgeResize:false,
    allowResizeUnselected:true,
    allowTextOverflow:true,
    autoSaveDelayMultiUser: 10,
    autoSaveDelaySingleUser: 2000,
    basicPlugins:{'/js/plugins/v2/mindmap.js':true},
    bleedHintColor: '#fb1d00',
    blockTypeIndent:function(type, fontSize) { if(type == 'p') return 0; return fontSize * (type=='ol' ? 3 : 2); },
    clipToPage:false,
    deactivatedDialogs: [],
    deactivatedUIHints: [],
    defaultColumnSpacing:72/4,
    defaultDPI:160,
    defaultGrid:20,
    defaultHAlign:'center',
    defaultImageClass: 'DefaultSquareBlock',
    defaultTextClass: 'DefaultTextBlockNew',
    defaultUnit: 'px',
    defaultVAlign:'middle',
    defaultZoom: 75,
    disabledProperties: {},
    drawOffPage: true,
    editorSpaceChecksDialogSelector:true,
    editorWantsTabs:true,//false, // I changed this to fix the tab and indent errors on chart
    editTextOutlineColor: 'palegoldenrod',
    extendedPageOptions:true,
    fontGroups:false,
    handleColor: '#883333',
    handleLineWidth: 1,
    hasBleed:false,
    hasEmbeddedPages: false,
    hasFacingPages:false,
    hasHeaderFooter:false,
    hasRulers:false,
    help: '/help/c/',
    hintBothLineColor: '#00cc00',
    hintEdgeLineColor: '#f78d1e',
    hintLineColor: '#0099ff',
    hintPanelLineColor: '#aaaaaa',
    hintLineWidth: 1,
    lineSpacingFactor:1,
    lockOptionBarWhenNoSelection: false,
    markupDefaults:{},
    outlineSize:6,
    overlayOffset:0,
    pagesHaveIndependentViewports: true,
    pageSizesAllowed: ['Letter', 'Legal', 'Executive', 'A3', 'A4', 'A5', 'Tabloid', 'Folio','Statement'],
    pageUnitsAllowed: ['in','cm', 'pt', 'px'],
    placeholderImageUrl: 'https://d2slcw3kip6qmk.cloudfront.net/app/webroot/img/img_placeholder.png',
    pluginGroups: [ 'Standard', 'Software', 'Business', 'Networking', 'Visual Content', 'Other' ],
    preferSelectedInHitTest: true,
    renderBackgroundItems: true,
    renderMetricsHintsForKeyboardInput: false,
    resizeHandleSize: 7,
    searchShouldChangePage: true,
    searchShouldShowMaster: true,
    serverDisableTimeout: 30,
    serverDisableTimeoutFocused: 600,
    showAlignmentHints:true,
    supportUrl: 'http://support.lucidchart.com',
    tempHintLineColor: '#ff3333',
    useChildrenCategories:true,
    useCMYKMode:false,
    useLinkPoints:true,
    viewportTitle: false,
    washOutInactive: true,
    zOrderOverrideAbove: ['state'],
    zOrderOverrideBelow: ['background'],
};
